### ISSUE TITLE
Better way to reload, pause, resume, stop, gp test all instances

### ISSUE THREAD

**Issue by Arturo-1212** [Arturo-1212/PTCGPB#1]
Right now it's using mouseclick to click on the buttons for each individual instance. There should be a better way. I tried adding the keybind to each ahk it only works for the last opened.

**Comment by azureWOX** [comment]
If your add ~ in front of the KeyPress Action it allows the KeyPress to populate trough all the system.

Example:

~F8:Close()

Now one KeyPress would close all instances
