### ISSUE TITLE
how can we edit the script to stop when a rainbow card (2-star) is found? Even in a non-god pack

### ISSUE THREAD

**Issue by carlox97** [Arturo-1212/PTCGPB#13]

**Comment by Legendary108** [comment]
I think that with this version, it is not possible to achieve that but let's hope in the next update Arturo includes a function to stop when a specific card or rarity is found.

**Comment by cstapdro** [comment]
I came here to ask the same question. This will be a great feature. Many people search for rainbow cards. Hope he adds it. Nevertheless, the bot is really nice atm.

**Comment by Arturo-1212** [comment]
Not a priority. If you reroll and join a rerolling community on discord you are swimming in god packs, so it's not really efficient to check and pick from single 2 star packs.

**Comment by PepeAlcaparra** [comment]
@Arturo-1212 Can you tell me your discord/rerolling discord community si I can join it? (Or send me an email to pepealcaparra750@gmail.com)

**Comment by Real96** [comment]
was this implemented in the end?
