### ISSUE TITLE
Get Stuck in 'Looking for Country/Menu/Delete3'

### ISSUE THREAD

**Issue by YuqingZhangMirror12** [Arturo-1212/PTCGPB#22]
Hi, thank you for your great work! I just got stuck in 'Looking for Country/Menu/Delete3' for around 1-2 mins. I ahere my settings in the following screenshots. I am using the old 2x version apk for game. 

![screen2](https://github.com/user-attachments/assets/f41006c9-60a6-40a4-bb12-9041e63cf5e8)
![screen1](https://github.com/user-attachments/assets/61071130-72d3-4046-a89b-ec8e523ee901)
![screen 3](https://github.com/user-attachments/assets/f24712f0-dbac-4b43-bfd1-a8b02637329f)

I am using only 1 monitor with 3840*2160 resolution plus 125% Windows system display. I double checked all previous settings but still confused if there is any point I missed. Thank you for your kind help!

**Comment by Arturo-1212** [comment]
I think something weird goes on with 4k displays. Lower your resolution to 2k and it should work. It doesn't seem to correctly resize the windows in 4k.

**Comment by YuqingZhangMirror12** [comment]
Thank you for replying! I switched my monitor to 2560*1440 display with 125% rescale. But still stuck at the following page when runing your script after clicking 'Start': 
![size](https://github.com/user-attachments/assets/1eb790b5-e3ee-4c68-b6dc-bafacb59eb78)

I double checked the cropped window size for MUMU simulator when runing your script (aftering clicking 'Arrange Windows' and 'Start', the window simulator window size is around 281*533. I wonder if this MUMU window size causes script failed. Thank you!

**Comment by YuqingZhangMirror12** [comment]
> I think something weird goes on with 4k displays. Lower your resolution to 2k and it should work. It doesn't seem to correctly resize the windows in 4k.

Thank you for replying! I switched my monitor to 2560*1440 display with 125% rescale. But still stuck at the following page when runing your script after clicking 'Start':

![size](https://github.com/user-attachments/assets/33464658-352b-44d0-b1dc-c3161ed13c4c)

I double checked the cropped window size for MUMU simulator when runing your script (aftering clicking 'Arrange Windows' and 'Start', the window simulator window size is around 281*533. I wonder if this MUMU window size causes script failed. Thank you!

**Comment by Arturo-1212** [comment]
Yes, your issue is related to the black bars on the top and bottom. There have been a few people where that hasn't been able to get resolved. Try restarting your pc after changing your resolution. Then try again. If the black bars show again then increase the size by dragging the bottom right corner and then decrease it to the smallest size. That should make the black bars go away and be the correct size. If it doesn't then I'm not sure what causes this for some people.

**Comment by YuqingZhangMirror12** [comment]
> Yes, your issue is related to the black bars on the top and bottom. There have been a few people where that hasn't been able to get resolved. Try restarting your pc after changing your resolution. Then try again. If the black bars show again then increase the size by dragging the bottom right corner and then decrease it to the smallest size. That should make the black bars go away and be the correct size. If it doesn't then I'm not sure what causes this for some people.

Thank you for your patience, I did resized the window to remove top and bottom black bars as you suggested, updated the latest bot, but still could not fix it. I wonder what is the window size on your PC? I would double check if resizing my MUMU windows exactly the same size as yours could help fix this issue. Thank you! 

![matrix](https://github.com/user-attachments/assets/91015e96-c67a-4e4a-8288-ee2b01c663f9)

![matrix resize](https://github.com/user-attachments/assets/68e26a00-b751-4d30-8803-05873fb41aec)

**Comment by YuqingZhangMirror12** [comment]
> > Yes, your issue is related to the black bars on the top and bottom. There have been a few people where that hasn't been able to get resolved. Try restarting your pc after changing your resolution. Then try again. If the black bars show again then increase the size by dragging the bottom right corner and then decrease it to the smallest size. That should make the black bars go away and be the correct size. If it doesn't then I'm not sure what causes this for some people.
> 
> Thank you for your patience, I did resized the window to remove top and bottom black bars as you suggested, updated the latest bot, but still could not fix it. I wonder what is the window size on your PC? I would double check if resizing my MUMU windows exactly the same size as yours could help fix this issue. Thank you!
> 
> ![matrix](https://private-user-images.githubusercontent.com/55674207/399249838-91015e96-c67a-4e4a-8288-ee2b01c663f9.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NzUyMzEsIm5iZiI6MTczNTU3NDkzMSwicGF0aCI6Ii81NTY3NDIwNy8zOTkyNDk4MzgtOTEwMTVlOTYtYzY3YS00ZTRhLTgyODgtZWUyYjAxYzY2M2Y5LlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDE2MDg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxOGNkZjlhMjEzMGUzNDg4ODc2OTIxM2Y0ZDExMmYxZTlkNjk2NjUzZDMwMjI4MjRiMzJmNjZmNjAyMzU0NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DRFcISIHtGcqvE35GNAY57w4i8L3KsyNNS-0u5edTCg)
> 
> ![matrix resize](https://private-user-images.githubusercontent.com/55674207/399249812-68e26a00-b751-4d30-8803-05873fb41aec.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NzUyMzEsIm5iZiI6MTczNTU3NDkzMSwicGF0aCI6Ii81NTY3NDIwNy8zOTkyNDk4MTItNjhlMjZhMDAtYjc1MS00ZDMwLTg4MDMtMDU4NzNmYjQxYWVjLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDE2MDg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZjVlY2EyMzJhOTZhMGRjNTM2ZmFkZDJhYmE5NDIwNDBiMWVjOWExNWQ4NmJkYzQ2YzY0ZDQ4NTM2YTFhMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4CfUAa2YOYAn9hpp8aouSXQ3dRjwVxh5Rs1SOqPogV8)

Just updated my Windows systems to 11 and fixed lmao

**Comment by YuqingZhangMirror12** [comment]
> Yes, your issue is related to the black bars on the top and bottom. There have been a few people where that hasn't been able to get resolved. Try restarting your pc after changing your resolution. Then try again. If the black bars show again then increase the size by dragging the bottom right corner and then decrease it to the smallest size. That should make the black bars go away and be the correct size. If it doesn't then I'm not sure what causes this for some people.

Just updated my Windows systems to 11 and fixed lmao
